### PR TITLE
use a single scheduler thread to track all timeouts

### PR DESCRIPTION
**Pull request by kch**
this implements #61.

would be great to get testers on it.

### CODE REVIEW

**Comment by evanphx** [comment]
I'm worried about this being merged in because it will make `rack-timeout` Ruby 2.0+ only, given all the syntax and features used.

**Comment by kch** [comment]
Other than syntax, what features?

Syntax can be changed. I suppose default named arguments can be shoehorned
into syntax.

**Comment by kch** [comment]
So looking over, the only 2.0+ feature I see is named parameters. That can be done away with.

@evanphx is your concern only MRI 1.9, or anything else that could affect rubinius / jruby?

**Comment by evanphx** [comment]
The usage of `private` before a `def` is 2.0+ I believe. At the very least I know it doesn't work in 1.8.

Perhaps I should have phrased it earlier as "should this patch make rack-timeout incompatible with ruby 1.8?"

**Comment by kch** [comment]
Oh we're already well incompatible with 1.8. I'm still willing to make an effort for 1.9, but that's been EOL'd too, so not sure for how long.

The def return value seems to be a 2.1 thing, so I guess that has to go.

**Comment by kch** [comment]
I'm gonna merge this in and get a new beta out. #78 is tracking betas.

@evanphx if you have any reservations still, let me know.

**Pull request merged**
