### PR TITLE
Let timeout thread die on its own instead of killing it

### PR DESCRIPTION
**Pull request by jvdp**
This prevents a nasty deadlock in Rails' logger's monitor which ultimately causes a timeout. I encountered this issue on a production app which runs on Puma with multiple threads.

The problem is reproducible with the following code:
```ruby
require "rack-timeout"
require "rack/test"
require "logger"

$logger = Logger.new(STDOUT)

Rack::Timeout::StageChangeLoggingObserver.logger = $logger

class SimpleLogger # stand-in for Rails::Rack::Logger
  def initialize(app)
    @app = app
  end

  def call(env)
    $logger.info "request started"
    @app.call(env)
  end
end

app = Rack::Builder.new do |b|
  b.use Rack::Timeout
  b.use SimpleLogger
  b.run lambda { |_env| [200, {}, ['ok']] }
end.to_app

request = Rack::MockRequest.new(app)

16.times.map do
  Thread.new do
    10_000.times do
      request.get("/")
    end
  end
end.each(&:join)
````

Or with the following test case (similar to what I originally submitted as [a Ruby issue](https://bugs.ruby-lang.org/issues/11040)):

````ruby
require "monitor"

$monitor = Monitor.new

def do_stuff
  $monitor.synchronize do
    print
  end
end

set_trace_func proc { |event, file, line, id, binding, classname|
  info = sprintf("%s %8s %s:%-2d %10s %8s", Thread.current, event, file, line, id, classname)
  color = 1 + Thread.current.object_id / 4 % 256
  puts "\e[38;5;#{color}m #{info} \e[39m"
}

1_000.times do
  thread = Thread.new do
    do_stuff
    sleep
  end
  do_stuff
  thread.kill
  thread.join
end
````

### CODE REVIEW

**Comment by kch** [comment]
This is probably the way to go, but I'm taking it to the next level™

:coffee: :coffee: :coffee: :coffee: :coffee: :coffee: :coffee: :coffee: :coffee: let's see what happens.

**Comment by jvdp** [comment]
You mean one thread that manages timeouts for all requests? (That would probably be a nicer solution.)

**Comment by kch** [comment]
Yeah. There's another issue for that (#61), and I even have some working code that does it.

But also, reversing the situation. Each new request is run in a thread off the main thread (possibly from a pool, working on a queue of request closures), and the main thread handles sending the responses back or sending a 503… and leaves the timed out thread to die on their own. (With a setting to be culled after some point or when the pool exhausts.) None of this is set in stone, but that's the idea forming.

It basically amounts to a rewrite. I'm working on something that I hope to put out there soon so we can get some validation.

**Comment by kch** [comment]
@jvdp see #82. It does the single thread to manage all the timeouts. Your test seems to work fine. I'll be merging it soon, just need to get some validation.

With that, I guess I can close this one out. Thanks for the patch anyhow.

(The other thing i mentioned is underway too, but it'll probably be an experimental branch or a whole new thing.)

**Pull request closed without merging**
