### PR TITLE
Remove rollbar module

### PR DESCRIPTION
**Pull request by andrehjr**
Rollbar module is currently broken when used with recent versions of the Rollbar gem. Monkeypatching the Rollbar seems like a bad practice as we can configure custom fingerprinting on Rollbar directly now. More details on #122 .

This PR:
- Removes rollbar module
- Adds instructions to configure Custom Fingerprinting directly on Rollbar.

Another approach would be to deprecate the module first, and then remove it. As this feature was optional and experimental, removing it seems better. Thoughts?

### CODE REVIEW

**Comment by wuputah** [comment]
It's break the `require` for anyone who was using it, which will cause the app to fail to boot. Could leave the file in there and have it echo an error message instead, but I'm not particularly bothered either way. As you said, it was an experimental feature. Not sure how much use it has in practice.

**Comment by andrehjr** [comment]
Added a `warn` message stating that the module was removed.

**Comment by wuputah** [comment]
That works for me! We can remove the file in `0.6.0`, if we ever get there.

Thanks so much for the contribution! :100:

**Comment by jjb** [comment]
This should perhaps be mentioned in https://github.com/heroku/rack-timeout/blob/master/UPGRADING.md

**Comment by wuputah** [comment]
Good point, I'll add something!

**Pull request merged**
